-- Migration: Harden categories table for production
-- Ensures created_at is generated by DB and adds constraints

-- Verify table exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name = 'categories'
    ) THEN
        -- Create table if it doesn't exist
        CREATE TABLE categories (
            id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            name VARCHAR(100) NOT NULL UNIQUE,
            description TEXT,
            color VARCHAR(20) DEFAULT '#4F46E5',
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        
        -- Create index on name for faster lookups
        CREATE INDEX idx_categories_name ON categories(name);
        
        RAISE NOTICE 'Categories table created';
    ELSE
        RAISE NOTICE 'Categories table already exists';
    END IF;
END $$;

-- Ensure created_at has default (DB-generated)
ALTER TABLE categories 
    ALTER COLUMN created_at SET DEFAULT NOW();

-- Ensure created_at is NOT NULL
ALTER TABLE categories 
    ALTER COLUMN created_at SET NOT NULL;

-- Add check constraint for name length (backend validates, but DB enforces)
ALTER TABLE categories 
    DROP CONSTRAINT IF EXISTS categories_name_length_check;
    
ALTER TABLE categories 
    ADD CONSTRAINT categories_name_length_check 
    CHECK (LENGTH(TRIM(name)) >= 2 AND LENGTH(name) <= 100);

-- Add check constraint for description length
ALTER TABLE categories 
    DROP CONSTRAINT IF EXISTS categories_description_length_check;
    
ALTER TABLE categories 
    ADD CONSTRAINT categories_description_length_check 
    CHECK (description IS NULL OR LENGTH(description) <= 500);

-- Add check constraint for color format
ALTER TABLE categories 
    DROP CONSTRAINT IF EXISTS categories_color_format_check;
    
ALTER TABLE categories 
    ADD CONSTRAINT categories_color_format_check 
    CHECK (color ~ '^#[0-9A-Fa-f]{6}$');

-- Ensure RLS is disabled (if using RLS, policies should allow INSERT)
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;

-- Verify structure
SELECT 
    column_name, 
    data_type, 
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'public' 
AND table_name = 'categories'
ORDER BY ordinal_position;

