import { useState, useRef, useEffect, useMemo } from 'react';
import type React from 'react';
import { useForm } from 'react-hook-form';
import type { FieldErrors, UseFormRegister } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Plus, X, ImagePlus, TrendingUp } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useLanguage } from '@/contexts/LanguageContext';
import { BarcodeScanButton } from '@/components/BarcodeScanner';
import type { Product } from './productTypes';

export interface ProductModalProps {
  product: Product | null;
  onClose: () => void;
  onSave: (product: Product, addAnother?: boolean) => void;
  categories: string[];
  suppliers: string[];
  units: string[];
  onRefreshCategories?: () => void;
}

type ProductFormData = {
  name: string;
  sku: string;
  barcode: string;
  category: string;
  unit: string;
  pack_size: number;
  pieces_per_carton: number;
  purchase_price: number;
  selling_price: number;
  stock_quantity: number;
  reorder_level: number;
  expiry_date: string;
  supplier: string;
  vat_inclusive: boolean;
  vat_rate: number;
  image_url: string;
  batch_number: string;
};

interface FieldBlockProps {
  label: string;
  required?: boolean;
  error?: string;
  hint?: string;
  children: React.ReactNode;
}

function FieldBlock({ label, required = false, error, hint, children }: FieldBlockProps) {
  return (
    <div>
      <label className="block text-sm font-medium text-slate-700 mb-1">
        {label}
        {required ? <span className="text-red-500 ml-0.5">*</span> : null}
      </label>
      {children}
      {error ? <p className="text-red-500 text-xs mt-1">{error}</p> : null}
      {!error && hint ? <p className="text-xs text-slate-500 mt-1">{hint}</p> : null}
    </div>
  );
}

interface BasicTabProps {
  t: (key: string) => string;
  register: UseFormRegister<ProductFormData>;
  errors: FieldErrors<ProductFormData>;
  imagePreview: string;
  fileInputRef: React.RefObject<HTMLInputElement>;
  handleImageUpload: (e: React.ChangeEvent<HTMLInputElement>) => void;
  handleBarcodeScan: (barcode: string) => void;
  categories: string[];
  unitOptions: string[];
  setSkuAutoGenerated: (next: boolean) => void;
  parseNumber: (value: unknown, fallback?: number) => number;
}

function BasicTab({
  t,
  register,
  errors,
  imagePreview,
  fileInputRef,
  handleImageUpload,
  handleBarcodeScan,
  categories,
  unitOptions,
  setSkuAutoGenerated,
  parseNumber,
}: BasicTabProps) {
  return (
    <TabsContent value="basic" className="space-y-4">
      <div className="flex items-start gap-4">
        <div className="flex-shrink-0">
          <div
            className="w-24 h-24 border-2 border-dashed border-slate-300 rounded-xl flex items-center justify-center cursor-pointer hover:border-primary-500 hover:bg-primary-50 transition-colors overflow-hidden"
            onClick={() => fileInputRef.current?.click()}
          >
            {imagePreview ? (
              <img src={imagePreview} alt="Product" className="w-full h-full object-cover" />
            ) : (
              <div className="text-center">
                <ImagePlus className="w-8 h-8 text-slate-400 mx-auto" />
                <span className="text-xs text-slate-500">{t('products.add_image')}</span>
              </div>
            )}
          </div>
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*"
            onChange={handleImageUpload}
            className="hidden"
          />
        </div>

        <div className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-4">
          <FieldBlock label={t('products.name')} required error={errors.name?.message}>
            <input
              type="text"
              {...register('name')}
              className={`input-field w-full focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all ${errors.name ? 'border-red-500 focus:ring-red-500' : ''}`}
            />
          </FieldBlock>
          <FieldBlock label={t('common.sku')} required error={errors.sku?.message}>
            <div className="flex gap-2">
              <input
                type="text"
                {...register('sku', {
                  onChange: () => setSkuAutoGenerated(false),
                })}
                className="input-field flex-1 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
              />
            </div>
          </FieldBlock>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">{t('products.barcode')}</label>
          <div className="flex gap-2">
            <input
              type="text"
              {...register('barcode')}
              className="input-field flex-1 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
              placeholder={t('products.scan_barcode')}
            />
            <BarcodeScanButton onScan={handleBarcodeScan} />
          </div>
        </div>
        <FieldBlock label={t('common.category')} required error={errors.category?.message}>
          <select
            {...register('category')}
            className="input-field w-full focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
          >
            <option value="">{t('products.select_category')}</option>
            {categories.map((cat: string) => (
              <option key={cat} value={cat}>{cat}</option>
            ))}
          </select>
        </FieldBlock>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">{t('common.unit')}</label>
          <select
            {...register('unit')}
            className="input-field w-full focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
          >
            {unitOptions.map((unit) => (
              <option key={unit} value={unit}>
                {unit}
              </option>
            ))}
          </select>
          <p className="text-xs text-slate-500 mt-1">{t('products.unit_hint')}</p>
        </div>
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">{t('products.pack_size')}</label>
          <input
            type="number"
            {...register('pack_size', {
              setValueAs: (value) => parseNumber(value, 1),
            })}
            className="input-field w-full focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
            min="1"
          />
          <p className="text-xs text-slate-500 mt-1">{t('products.pack_size_hint')}</p>
        </div>
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">{t('common.pcs_ctn')}</label>
          <input
            type="number"
            {...register('pieces_per_carton', {
              setValueAs: (value) => parseNumber(value, 1),
            })}
            className="input-field w-full focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
            min="1"
            placeholder="যেমন: ২৪"
          />
          <p className="text-xs text-slate-500 mt-1">{t('products.carton_hint')}</p>
        </div>
      </div>
    </TabsContent>
  );
}

interface PricingTabProps {
  t: (key: string) => string;
  register: UseFormRegister<ProductFormData>;
  errors: FieldErrors<ProductFormData>;
  parseNumber: (value: unknown, fallback?: number) => number;
  profitAmount: number;
  profitPercent: string;
  vatInclusive: boolean;
}

function PricingTab({
  t,
  register,
  errors,
  parseNumber,
  profitAmount,
  profitPercent,
  vatInclusive,
}: PricingTabProps) {
  return (
    <TabsContent value="pricing" className="space-y-4">
      <div className="bg-muted/40 rounded-xl p-3">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <FieldBlock
            label={`${t('products.purchase_price')} (৳)`}
            required
            error={errors.purchase_price?.message}
            hint={t('products.purchase_hint')}
          >
            <input
              type="number"
              {...register('purchase_price', {
                setValueAs: (value) => parseNumber(value),
              })}
              className={`input-field w-full ${errors.purchase_price ? 'border-red-500' : ''}`}
              min="0"
              step="0.01"
              placeholder="কার্টন দাম ÷ পিস"
            />
          </FieldBlock>
          <FieldBlock
            label={`${t('products.selling_price')} (৳)`}
            required
            error={errors.selling_price?.message}
            hint={t('products.selling_hint')}
          >
            <input
              type="number"
              {...register('selling_price', {
                setValueAs: (value) => parseNumber(value),
              })}
              className={`input-field w-full ${errors.selling_price ? 'border-red-500' : ''}`}
              min="0"
              step="0.01"
            />
          </FieldBlock>
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">{t('products.profit_margin')}</label>
            <div className={`input-field w-full flex items-center gap-2 ${profitAmount >= 0 ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'}`}>
              <TrendingUp className={`w-4 h-4 ${profitAmount >= 0 ? 'text-green-600' : 'text-red-600'}`} />
              <span className={`font-medium ${profitAmount >= 0 ? 'text-green-700' : 'text-red-700'}`}>
                ৳{profitAmount} ({profitPercent}%)
              </span>
            </div>
            <p className="text-xs text-slate-500 mt-1">{t('products.profit_hint')}</p>
          </div>
        </div>

        <div className="flex items-center gap-4 mt-3 pt-3 border-t border-border">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              {...register('vat_inclusive')}
              className="w-4 h-4 text-primary-600 rounded focus:ring-primary-500"
            />
            <span className="text-sm text-slate-700">{t('products.vat_inclusive')}</span>
          </label>
          {vatInclusive && (
            <div className="flex items-center gap-2">
              <label className="text-sm text-slate-700">{t('products.vat_rate')}:</label>
              <input
                type="number"
                {...register('vat_rate', {
                  setValueAs: (value) => parseNumber(value),
                })}
                className="input-field w-20"
                min="0"
                max="100"
              />
              <span className="text-sm text-slate-500">%</span>
            </div>
          )}
        </div>
      </div>
    </TabsContent>
  );
}

interface InventoryTabProps {
  t: (key: string) => string;
  register: UseFormRegister<ProductFormData>;
  errors: FieldErrors<ProductFormData>;
  parseNumber: (value: unknown, fallback?: number) => number;
  cartonCount: number;
  setCartonCount: (value: number) => void;
  autoCalcStock: boolean;
  setAutoCalcStock: (value: boolean) => void;
  batchHasValue: boolean;
  expiryRequired: boolean;
  setBatchAutoGenerated: (value: boolean) => void;
  suppliers: string[];
}

function InventoryTab({
  t,
  register,
  errors,
  parseNumber,
  cartonCount,
  setCartonCount,
  autoCalcStock,
  setAutoCalcStock,
  batchHasValue,
  expiryRequired,
  setBatchAutoGenerated,
  suppliers,
}: InventoryTabProps) {
  return (
    <TabsContent value="inventory" className="space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">{t('products.carton_count')}</label>
          <input
            type="number"
            value={cartonCount}
            onChange={(e) => {
              const nextCartons = Number(e.target.value);
              setCartonCount(Number.isNaN(nextCartons) ? 0 : nextCartons);
            }}
            className="input-field w-full"
            min="0"
            placeholder="যেমন: ১০"
          />
          <p className="text-xs text-slate-500 mt-1">{t('products.carton_count_hint')}</p>
        </div>
        <FieldBlock
          label={t('products.stock_quantity')}
          required
          error={errors.stock_quantity?.message}
          hint={t('products.stock_hint')}
        >
          <input
            type="number"
            {...register('stock_quantity', {
              setValueAs: (value) => parseNumber(value),
            })}
            className={`input-field w-full ${errors.stock_quantity ? 'border-red-500' : ''}`}
            min="0"
            placeholder="১০ কার্টন = ২৪০"
            readOnly={autoCalcStock && cartonCount > 0}
          />
          <label className="flex items-center gap-2 mt-2 text-xs text-slate-600">
            <input
              type="checkbox"
              checked={autoCalcStock}
              onChange={(e) => setAutoCalcStock(e.target.checked)}
              className="w-4 h-4 text-primary-600 rounded focus:ring-primary-500"
            />
            {t('products.auto_calc')}
          </label>
        </FieldBlock>
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">
            {t('products.reorder_level')}
          </label>
          <input
            type="number"
            {...register('reorder_level', {
              setValueAs: (value) => parseNumber(value),
            })}
            className="input-field w-full"
            min="0"
            placeholder="কম হলে সতর্কতা"
          />
          <p className="text-xs text-slate-500 mt-1">{t('products.reorder_hint')}</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">{t('products.batch_number')}</label>
          <input
            type="text"
            {...register('batch_number', {
              onChange: () => setBatchAutoGenerated(false),
            })}
            className="input-field w-full"
            placeholder="যেমন: BT-2024-001"
          />
          <p className="text-xs text-slate-500 mt-1">{t('products.batch_hint')}</p>
          {!batchHasValue && (
            <p className="text-xs text-slate-500 mt-1">
              {t('products.batch_auto_hint')}
            </p>
          )}
        </div>
        <FieldBlock
          label={t('products.expiry_date')}
          required={expiryRequired}
          error={errors.expiry_date?.message}
          hint={t('products.expiry_hint')}
        >
          <input
            type="date"
            {...register('expiry_date')}
            className={`input-field w-full ${errors.expiry_date ? 'border-red-500' : ''}`}
            required={expiryRequired}
          />
        </FieldBlock>
      </div>

      <div>
        <label className="block text-sm font-medium text-slate-700 mb-1">{t('products.supplier')}</label>
        <select
          {...register('supplier')}
          className="input-field w-full"
        >
          <option value="">{t('products.select_supplier')}</option>
          {suppliers.map((sup: string) => (
            <option key={sup} value={sup}>{sup}</option>
          ))}
        </select>
      </div>
    </TabsContent>
  );
}

interface AdvancedTabProps {
  templateName: string;
  setTemplateName: (value: string) => void;
  variantName: string;
  setVariantName: (value: string) => void;
  variantSku: string;
  setVariantSku: (value: string) => void;
  baseUom: string;
  setBaseUom: (value: string) => void;
  uomFrom: string;
  setUomFrom: (value: string) => void;
  uomTo: string;
  setUomTo: (value: string) => void;
  uomFactor: number;
  setUomFactor: (value: number) => void;
}

function AdvancedTab({
  templateName,
  setTemplateName,
  variantName,
  setVariantName,
  variantSku,
  setVariantSku,
  baseUom,
  setBaseUom,
  uomFrom,
  setUomFrom,
  uomTo,
  setUomTo,
  uomFactor,
  setUomFactor,
}: AdvancedTabProps) {
  return (
    <TabsContent value="advanced" className="space-y-4">
      <div className="rounded-xl border border-border bg-muted/30 p-3">
        <h3 className="mb-2 text-sm font-semibold text-foreground">Variant Setup</h3>
        <div className="grid grid-cols-1 gap-3 md:grid-cols-3">
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">Template Name</label>
            <input value={templateName} onChange={(e) => setTemplateName(e.target.value)} className="input-field w-full" />
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">Variant Name</label>
            <input value={variantName} onChange={(e) => setVariantName(e.target.value)} className="input-field w-full" />
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">Variant SKU</label>
            <input value={variantSku} onChange={(e) => setVariantSku(e.target.value)} className="input-field w-full" />
          </div>
        </div>
      </div>

      <div className="rounded-xl border border-border bg-muted/30 p-3">
        <h3 className="mb-2 text-sm font-semibold text-foreground">UOM Conversion</h3>
        <div className="grid grid-cols-1 gap-3 md:grid-cols-4">
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">Base UOM</label>
            <input value={baseUom} onChange={(e) => setBaseUom(e.target.value)} className="input-field w-full" />
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">From</label>
            <input value={uomFrom} onChange={(e) => setUomFrom(e.target.value)} className="input-field w-full" />
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">To</label>
            <input value={uomTo} onChange={(e) => setUomTo(e.target.value)} className="input-field w-full" />
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">Factor</label>
            <input
              type="number"
              min="0.000001"
              step="0.000001"
              value={uomFactor}
              onChange={(e) => setUomFactor(Number(e.target.value))}
              className="input-field w-full"
            />
          </div>
        </div>
        <p className="mt-2 text-xs text-muted-foreground">
          This section prepares variant/UOM metadata for ERP-style workflow.
        </p>
      </div>
    </TabsContent>
  );
}

export function ProductModal({ product, onClose, onSave, categories, suppliers, units, onRefreshCategories }: ProductModalProps) {
  const { t } = useLanguage();

  const productSchema = useMemo(
    () =>
      z
        .object({
          name: z.string().trim().min(1, t('products.validation.name_required')),
          sku: z.string().trim().min(1, t('products.validation.sku_required')),
          barcode: z.string(),
          category: z.string().trim().min(1, t('products.validation.category_required')),
          unit: z.string(),
          pack_size: z.number().min(1, t('products.validation.pack_size_min')),
          pieces_per_carton: z.number().min(1, t('products.validation.pieces_per_carton_min')),
          purchase_price: z.number().min(0, t('products.validation.price_negative')),
          selling_price: z.number().min(0, t('products.validation.price_negative')),
          stock_quantity: z.number().min(0, t('products.validation.stock_negative')),
          reorder_level: z.number().min(0),
          expiry_date: z.string(),
          supplier: z.string(),
          vat_inclusive: z.boolean(),
          vat_rate: z.number().min(0).max(100),
          image_url: z.string(),
          batch_number: z.string(),
        })
        .superRefine((values, ctx) => {
          if (values.batch_number?.trim() && !values.expiry_date) {
            ctx.addIssue({
              code: z.ZodIssueCode.custom,
              message: t('products.expiry_required'),
              path: ['expiry_date'],
            });
          }
        }),
    [t]
  );
  const parseNumber = (value: unknown, fallback = 0) => {
    const n = Number(value);
    return Number.isFinite(n) ? n : fallback;
  };

  const initialValues: ProductFormData = {
    name: product?.name ?? '',
    sku: product?.sku ?? '',
    barcode: product?.barcode ?? '',
    category: product?.category ?? '',
    unit: product?.unit ?? 'Pack',
    pack_size: product?.pack_size ?? 1,
    pieces_per_carton: product?.pieces_per_carton ?? 24,
    purchase_price: product?.purchase_price ?? 0,
    selling_price: product?.selling_price ?? 0,
    stock_quantity: product?.stock_quantity ?? 0,
    reorder_level: product?.reorder_level ?? 10,
    expiry_date: product?.expiry_date ?? '',
    supplier: product?.supplier ?? '',
    vat_inclusive: product?.vat_inclusive ?? false,
    vat_rate: product?.vat_rate ?? 0,
    image_url: product?.image_url ?? '',
    batch_number: product?.batch_number ?? '',
  };

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    reset,
    setError,
    clearErrors,
    formState: { errors },
  } = useForm<ProductFormData>({
    resolver: zodResolver(productSchema),
    defaultValues: initialValues,
  });

  // Refetch categories when modal opens to ensure latest data
  useEffect(() => {
    if (onRefreshCategories) {
      onRefreshCategories();
    }
  }, []); // Run once when modal opens

  const formData = watch();
  const [skuAutoGenerated, setSkuAutoGenerated] = useState(!product?.sku);
  const [batchAutoGenerated, setBatchAutoGenerated] = useState(!product?.batch_number);
  const [cartonCount, setCartonCount] = useState(0);
  const [autoCalcStock, setAutoCalcStock] = useState(!product);
  const [imagePreview, setImagePreview] = useState<string>(product?.image_url || '');
  const [activeTab, setActiveTab] = useState<'basic' | 'pricing' | 'inventory' | 'advanced'>('basic');
  const [templateName, setTemplateName] = useState(product?.name || '');
  const [variantName, setVariantName] = useState(product?.name || '');
  const [variantSku, setVariantSku] = useState(product?.sku || '');
  const [baseUom, setBaseUom] = useState(product?.unit || 'Pack');
  const [uomFrom, setUomFrom] = useState('Carton');
  const [uomTo, setUomTo] = useState(product?.unit || 'Pack');
  const [uomFactor, setUomFactor] = useState<number>(1);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const unitOptions = useMemo(() => {
    const fallbackUnits = ['Pack', 'Bag', 'Box', 'Piece', 'Carton'];
    const baseUnits = units.length > 0 ? units : fallbackUnits;
    const currentUnit = formData.unit;
    if (currentUnit && !baseUnits.includes(currentUnit)) {
      return [currentUnit, ...baseUnits];
    }
    return baseUnits;
  }, [units, formData.unit]);

  const generateBatchNumber = () => {
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const rand = Math.random().toString(36).slice(2, 6).toUpperCase();
    return `B${year}${month}-${rand}`;
  };

  const buildSku = () => {
    if (!formData.name || !formData.category) return '';
    const nameCode = formData.name.substring(0, 3).toUpperCase().replace(/\s/g, '');
    const catCode = formData.category.substring(0, 3).toUpperCase().replace(/\s/g, '');
    const randomNum = Math.floor(Math.random() * 900) + 100;
    return `${nameCode}-${catCode}-${randomNum}`;
  };

  const buildFallbackSku = () => {
    const randomNum = Math.floor(Math.random() * 900) + 100;
    return `PRD-GEN-${randomNum}`;
  };

  const handleBarcodeScan = (barcode: string) => {
    setValue('barcode', barcode, { shouldDirty: true });
  };

  useEffect(() => {
    const shouldAutoGenerate = !formData.sku || skuAutoGenerated;
    if (!shouldAutoGenerate) return;
    const nextSku = buildSku();
    if (!nextSku) return;
    setValue('sku', nextSku, { shouldDirty: true });
    setSkuAutoGenerated(true);
  }, [formData.name, formData.category, formData.sku, skuAutoGenerated, setValue]);

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64 = reader.result as string;
        setImagePreview(base64);
        setValue('image_url', base64, { shouldDirty: true });
      };
      reader.readAsDataURL(file);
    }
  };

  const profitAmount = (formData.selling_price || 0) - (formData.purchase_price || 0);
  const profitPercent = formData.purchase_price && formData.purchase_price > 0
    ? ((profitAmount / formData.purchase_price) * 100).toFixed(1)
    : '0';

  const updateStockFromCartons = (nextCartonCount: number, nextPiecesPerCarton: number) => {
    const cartons = Number(nextCartonCount) || 0;
    const pieces = Number(nextPiecesPerCarton) || 0;
    if (cartons <= 0 || pieces <= 0) {
      return;
    }
    const nextStock = Math.max(0, cartons * pieces);
    if (formData.stock_quantity !== nextStock) {
      setValue('stock_quantity', nextStock, { shouldDirty: true, shouldValidate: true });
    }
  };

  useEffect(() => {
    if (!autoCalcStock) return;
    updateStockFromCartons(cartonCount, formData.pieces_per_carton || 0);
  }, [autoCalcStock, cartonCount, formData.pieces_per_carton]);

  useEffect(() => {
    if (product) return;
    if (!formData.sku) {
      const nextSku = buildSku();
      const skuToUse = nextSku || buildFallbackSku();
      setValue('sku', skuToUse, { shouldDirty: true });
      setSkuAutoGenerated(true);
    }
    if (!formData.batch_number) {
      const nextBatch = generateBatchNumber();
      setValue('batch_number', nextBatch, { shouldDirty: true });
      setBatchAutoGenerated(true);
    }
  }, [product, formData.sku, formData.batch_number, setValue]);

  const batchHasValue = !!(formData.batch_number && formData.batch_number.trim() !== '');
  const expiryRequired = batchHasValue && !batchAutoGenerated;

  const submitProduct = (values: ProductFormData, addAnother = false) => {
    const nextFormData = { ...values };
    if (!nextFormData.batch_number?.trim() && nextFormData.expiry_date) {
      nextFormData.batch_number = generateBatchNumber();
      setValue('batch_number', nextFormData.batch_number, { shouldDirty: true });
    }

    const hasBatch = !!nextFormData.batch_number?.trim();
    if (hasBatch && !nextFormData.expiry_date) {
      setError('expiry_date', {
        type: 'manual',
        message: t('products.expiry_required'),
      });
      return;
    }

    onSave(nextFormData as Product, addAnother);

    if (!addAnother) return;

    reset({
      ...initialValues,
      name: '',
      sku: '',
      barcode: '',
      category: values.category,
      unit: values.unit,
      pack_size: 1,
      pieces_per_carton: 24,
      purchase_price: 0,
      selling_price: 0,
      stock_quantity: 0,
      reorder_level: 10,
      batch_number: generateBatchNumber(),
      expiry_date: '',
      supplier: values.supplier,
      vat_inclusive: values.vat_inclusive,
      vat_rate: values.vat_rate,
      image_url: '',
    });
    setCartonCount(0);
    setAutoCalcStock(true);
    setSkuAutoGenerated(true);
    setBatchAutoGenerated(true);
    setImagePreview('');
    clearErrors();
  };

  return (
      <div className="dh-modal-overlay">
      <div className="dh-modal-panel w-full max-w-3xl max-h-[90vh] overflow-y-auto">
        <div className="p-4 border-b border-border flex items-center justify-between gap-2">
          <h2 className="text-lg font-semibold text-foreground">
            {product ? t('products.edit') : t('products.add_new')}
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
            aria-label="Close"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit((values) => submitProduct(values, false))} className="p-4 space-y-4">
          <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as typeof activeTab)}>
            <TabsList className="mb-2 grid h-auto w-full grid-cols-2 gap-1 md:grid-cols-4">
              <TabsTrigger value="basic">Basic</TabsTrigger>
              <TabsTrigger value="pricing">Pricing</TabsTrigger>
              <TabsTrigger value="inventory">Inventory</TabsTrigger>
              <TabsTrigger value="advanced">Advanced</TabsTrigger>
            </TabsList>
            <p className="mb-3 text-xs text-muted-foreground">
              Quick entry flow with tabbed sections for faster product setup.
            </p>
            <BasicTab
              t={t}
              register={register}
              errors={errors}
              imagePreview={imagePreview}
              fileInputRef={fileInputRef}
              handleImageUpload={handleImageUpload}
              handleBarcodeScan={handleBarcodeScan}
              categories={categories}
              unitOptions={unitOptions}
              setSkuAutoGenerated={setSkuAutoGenerated}
              parseNumber={parseNumber}
            />

            <PricingTab
              t={t}
              register={register}
              errors={errors}
              parseNumber={parseNumber}
              profitAmount={profitAmount}
              profitPercent={profitPercent}
              vatInclusive={formData.vat_inclusive}
            />

            <InventoryTab
              t={t}
              register={register}
              errors={errors}
              parseNumber={parseNumber}
              cartonCount={cartonCount}
              setCartonCount={setCartonCount}
              autoCalcStock={autoCalcStock}
              setAutoCalcStock={setAutoCalcStock}
              batchHasValue={batchHasValue}
              expiryRequired={expiryRequired}
              setBatchAutoGenerated={setBatchAutoGenerated}
              suppliers={suppliers}
            />

            <AdvancedTab
              templateName={templateName}
              setTemplateName={setTemplateName}
              variantName={variantName}
              setVariantName={setVariantName}
              variantSku={variantSku}
              setVariantSku={setVariantSku}
              baseUom={baseUom}
              setBaseUom={setBaseUom}
              uomFrom={uomFrom}
              setUomFrom={setUomFrom}
              uomTo={uomTo}
              setUomTo={setUomTo}
              uomFactor={uomFactor}
              setUomFactor={setUomFactor}
            />
          </Tabs>

          {/* Action Buttons */}
          <div className="flex justify-end gap-2 pt-4 border-t border-border">
            <button type="button" onClick={onClose} className="btn-secondary">
              {t('products.cancel')}
            </button>
            {!product && (
              <button
                type="button"
                onClick={handleSubmit((values) => submitProduct(values, true))}
                className="btn-secondary flex items-center gap-2"
              >
                <Plus className="w-4 h-4" />
                {t('products.add_another')}
              </button>
            )}
            <button type="submit" className="btn-primary">
              {product ? t('products.update') : t('products.save')}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
